/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = RadioManager.Client.SwaggerDateConverter;

namespace RadioManager.Model
{
    /// <summary>
    /// EPGResults
    /// </summary>
    [DataContract]
        public partial class EPGResults :  IEquatable<EPGResults>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EPGResults" /> class.
        /// </summary>
        /// <param name="days">days (required).</param>
        /// <param name="nextPageUrl">nextPageUrl (required).</param>
        /// <param name="prevPageUrl">prevPageUrl (required).</param>
        public EPGResults(List<BroadcastEPGDay> days = default(List<BroadcastEPGDay>), string nextPageUrl = default(string), string prevPageUrl = default(string))
        {
            // to ensure "days" is required (not null)
            if (days == null)
            {
                throw new InvalidDataException("days is a required property for EPGResults and cannot be null");
            }
            else
            {
                this.Days = days;
            }
            // to ensure "nextPageUrl" is required (not null)
            if (nextPageUrl == null)
            {
                throw new InvalidDataException("nextPageUrl is a required property for EPGResults and cannot be null");
            }
            else
            {
                this.NextPageUrl = nextPageUrl;
            }
            // to ensure "prevPageUrl" is required (not null)
            if (prevPageUrl == null)
            {
                throw new InvalidDataException("prevPageUrl is a required property for EPGResults and cannot be null");
            }
            else
            {
                this.PrevPageUrl = prevPageUrl;
            }
        }
        
        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name="days", EmitDefaultValue=false)]
        public List<BroadcastEPGDay> Days { get; set; }

        /// <summary>
        /// Gets or Sets NextPageUrl
        /// </summary>
        [DataMember(Name="next_page_url", EmitDefaultValue=false)]
        public string NextPageUrl { get; set; }

        /// <summary>
        /// Gets or Sets PrevPageUrl
        /// </summary>
        [DataMember(Name="prev_page_url", EmitDefaultValue=false)]
        public string PrevPageUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EPGResults {\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  NextPageUrl: ").Append(NextPageUrl).Append("\n");
            sb.Append("  PrevPageUrl: ").Append(PrevPageUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EPGResults);
        }

        /// <summary>
        /// Returns true if EPGResults instances are equal
        /// </summary>
        /// <param name="input">Instance of EPGResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EPGResults input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Days == input.Days ||
                    this.Days != null &&
                    input.Days != null &&
                    this.Days.SequenceEqual(input.Days)
                ) && 
                (
                    this.NextPageUrl == input.NextPageUrl ||
                    (this.NextPageUrl != null &&
                    this.NextPageUrl.Equals(input.NextPageUrl))
                ) && 
                (
                    this.PrevPageUrl == input.PrevPageUrl ||
                    (this.PrevPageUrl != null &&
                    this.PrevPageUrl.Equals(input.PrevPageUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Days != null)
                    hashCode = hashCode * 59 + this.Days.GetHashCode();
                if (this.NextPageUrl != null)
                    hashCode = hashCode * 59 + this.NextPageUrl.GetHashCode();
                if (this.PrevPageUrl != null)
                    hashCode = hashCode * 59 + this.PrevPageUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
