/* 
 * Pluxbox Radiomanager Client
 *
 * Pluxbox RadioManager gives you the power, flexibility and speed you always wanted in a lightweight and easy-to-use web-based radio solution. With Pluxbox RadioManager you can organise your radio workflow and automate your omnichannel communication with your listeners. We offer wide range specialised services for the radio and connections like Hybrid Radio, Visual Radio, your website and social media without losing focus on your broadcast. For more information visit https://pluxbox.com
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing ContactOutputOnly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactOutputOnlyTests
    {
        // TODO uncomment below to declare an instance variable for ContactOutputOnly
        //private ContactOutputOnly instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactOutputOnly
            //instance = new ContactOutputOnly();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactOutputOnly
        /// </summary>
        [Test]
        public void ContactOutputOnlyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactOutputOnly
            //Assert.IsInstanceOfType<ContactOutputOnly> (instance, "variable 'instance' is a ContactOutputOnly");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Test]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'ExternalStationId'
        /// </summary>
        [Test]
        public void ExternalStationIdTest()
        {
            // TODO unit test for the property 'ExternalStationId'
        }

    }

}
