/* 
 * RadioManager
 *
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing ContactRelationsItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactRelationsItemsTests
    {
        // TODO uncomment below to declare an instance variable for ContactRelationsItems
        //private ContactRelationsItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactRelationsItems
            //instance = new ContactRelationsItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactRelationsItems
        /// </summary>
        [Test]
        public void ContactRelationsItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactRelationsItems
            //Assert.IsInstanceOfType<ContactRelationsItems> (instance, "variable 'instance' is a ContactRelationsItems");
        }


        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }

    }

}
