/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing GenreResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GenreResultsTests
    {
        // TODO uncomment below to declare an instance variable for GenreResults
        //private GenreResults instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenreResults
            //instance = new GenreResults();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenreResults
        /// </summary>
        [Test]
        public void GenreResultsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenreResults
            //Assert.IsInstanceOfType<GenreResults> (instance, "variable 'instance' is a GenreResults");
        }


        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Test]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'LastPage'
        /// </summary>
        [Test]
        public void LastPageTest()
        {
            // TODO unit test for the property 'LastPage'
        }
        /// <summary>
        /// Test the property 'NextPageUrl'
        /// </summary>
        [Test]
        public void NextPageUrlTest()
        {
            // TODO unit test for the property 'NextPageUrl'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'PerPage'
        /// </summary>
        [Test]
        public void PerPageTest()
        {
            // TODO unit test for the property 'PerPage'
        }
        /// <summary>
        /// Test the property 'PrevPageUrl'
        /// </summary>
        [Test]
        public void PrevPageUrlTest()
        {
            // TODO unit test for the property 'PrevPageUrl'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
