/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing GenreRelations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GenreRelationsTests
    {
        // TODO uncomment below to declare an instance variable for GenreRelations
        //private GenreRelations instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenreRelations
            //instance = new GenreRelations();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenreRelations
        /// </summary>
        [Test]
        public void GenreRelationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenreRelations
            //Assert.IsInstanceOfType<GenreRelations> (instance, "variable 'instance' is a GenreRelations");
        }


        /// <summary>
        /// Test the property 'Broadcasts'
        /// </summary>
        [Test]
        public void BroadcastsTest()
        {
            // TODO unit test for the property 'Broadcasts'
        }
        /// <summary>
        /// Test the property 'Programs'
        /// </summary>
        [Test]
        public void ProgramsTest()
        {
            // TODO unit test for the property 'Programs'
        }

    }

}
