/* 
 * RadioManager
 *
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing InlineResponse401
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse401Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse401
        //private InlineResponse401 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse401
            //instance = new InlineResponse401();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse401
        /// </summary>
        [Test]
        public void InlineResponse401InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse401
            //Assert.IsInstanceOfType<InlineResponse401> (instance, "variable 'instance' is a InlineResponse401");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ErrorDescription'
        /// </summary>
        [Test]
        public void ErrorDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDescription'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

    }

}
