/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing InviteUserSuccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InviteUserSuccessTests
    {
        // TODO uncomment below to declare an instance variable for InviteUserSuccess
        //private InviteUserSuccess instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InviteUserSuccess
            //instance = new InviteUserSuccess();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InviteUserSuccess
        /// </summary>
        [Test]
        public void InviteUserSuccessInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InviteUserSuccess
            //Assert.IsInstanceOfType<InviteUserSuccess> (instance, "variable 'instance' is a InviteUserSuccess");
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
