/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing ModelTypeOutputOnly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelTypeOutputOnlyTests
    {
        // TODO uncomment below to declare an instance variable for ModelTypeOutputOnly
        //private ModelTypeOutputOnly instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelTypeOutputOnly
            //instance = new ModelTypeOutputOnly();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelTypeOutputOnly
        /// </summary>
        [Test]
        public void ModelTypeOutputOnlyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelTypeOutputOnly
            //Assert.IsInstanceOfType<ModelTypeOutputOnly> (instance, "variable 'instance' is a ModelTypeOutputOnly");
        }

        /// <summary>
        /// Test the property 'ExternalStationId'
        /// </summary>
        [Test]
        public void ExternalStationIdTest()
        {
            // TODO unit test for the property 'ExternalStationId'
        }

    }

}
