/* 
 * Pluxbox Radiomanager Client
 *
 * Pluxbox RadioManager gives you the power, flexibility and speed you always wanted in a lightweight and easy-to-use web-based radio solution. With Pluxbox RadioManager you can organise your radio workflow and automate your omnichannel communication with your listeners. We offer wide range specialised services for the radio and connections like Hybrid Radio, Visual Radio, your website and social media without losing focus on your broadcast. For more information visit https://pluxbox.com
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing Presenter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PresenterTests
    {
        // TODO uncomment below to declare an instance variable for Presenter
        //private Presenter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Presenter
            //instance = new Presenter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Presenter
        /// </summary>
        [Test]
        public void PresenterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Presenter
            //Assert.IsInstanceOfType<Presenter> (instance, "variable 'instance' is a Presenter");
        }

        /// <summary>
        /// Test the property 'ModelTypeId'
        /// </summary>
        [Test]
        public void ModelTypeIdTest()
        {
            // TODO unit test for the property 'ModelTypeId'
        }
        /// <summary>
        /// Test the property 'FieldValues'
        /// </summary>
        [Test]
        public void FieldValuesTest()
        {
            // TODO unit test for the property 'FieldValues'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
