/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing ProgramFieldValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProgramFieldValuesTests
    {
        // TODO uncomment below to declare an instance variable for ProgramFieldValues
        //private ProgramFieldValues instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProgramFieldValues
            //instance = new ProgramFieldValues();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProgramFieldValues
        /// </summary>
        [Test]
        public void ProgramFieldValuesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProgramFieldValues
            //Assert.IsInstanceOfType<ProgramFieldValues> (instance, "variable 'instance' is a ProgramFieldValues");
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

    }

}
