/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadioManager.Api;
using RadioManager.Model;
using RadioManager.Client;
using System.Reflection;

namespace RadioManager.Test
{
    /// <summary>
    ///  Class for testing TagRelationsBroadcastsParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TagRelationsBroadcastsParamsTests
    {
        // TODO uncomment below to declare an instance variable for TagRelationsBroadcastsParams
        //private TagRelationsBroadcastsParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TagRelationsBroadcastsParams
            //instance = new TagRelationsBroadcastsParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TagRelationsBroadcastsParams
        /// </summary>
        [Test]
        public void TagRelationsBroadcastsParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TagRelationsBroadcastsParams
            //Assert.IsInstanceOfType<TagRelationsBroadcastsParams> (instance, "variable 'instance' is a TagRelationsBroadcastsParams");
        }

        /// <summary>
        /// Test the property 'TagId'
        /// </summary>
        [Test]
        public void TagIdTest()
        {
            // TODO unit test for the property 'TagId'
        }

    }

}
